### ISSUE TITLE
Enable manifpy compilation when ROBOTOLOGY_USES_PYTHON is enabled

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild#799]
Differently from most C++/Python projects that we support, `manif` does not permit to install from CMake its Python bindings (see https://github.com/artivis/manif/blob/0.0.4/python/CMakeLists.txt, and do not get afraid for the `EIGEN_DEFAULT_TO_ROW_MAJOR` as I was : ) ). Instead, the "installation" is happening in the [`setup.py`](https://github.com/artivis/manif/blob/0.0.4/setup.py#L49) by setting the `CMAKE_LIBRARY_OUTPUT_DIRECTORY` variable to the desired installation location. 

So the options are:
* Install manifpy by invoking the setup.py and specify manually the location where it should be installed
* Patching the CMake build script of manif to permit to install the Python bindings directly from C++

Any opinion @GiulioRomualdi @diegoferigo ?

**Comment by traversaro** [comment]
Sister issue: https://github.com/conda-forge/manif-feedstock/issues/3 .

**Comment by diegoferigo** [comment]
I'm not really an expert of packaging for conda. If I understood correctly, instead of getting files from the CMake install tree as we do for other projects, we have to pass through setuptools that will install the Python files in the enabled site-packages, and then package this folder with conda. Correct?

If this is ok in the conda-side, it seems to be the easiest solution at the moment. Note that I recently opened https://github.com/artivis/manif/issues/228 that, depending if and how it will get implemented, could involve a new CMake machinery similar to what we are are used to have in our hybrid projects.

**Comment by traversaro** [comment]
To clarify, the issue on manifpy packaging in conda is https://github.com/conda-forge/manif-feedstock/issues/3 . This one is to install manifpy as part of the robotology-superbuild.

**Comment by traversaro** [comment]
Calling a setup.py from the [`Buildmanif.cmake` file](https://github.com/robotology/robotology-superbuild/blob/master/cmake/Buildmanif.cmake) or even creating a `Buildmanifpy.cmake`  seems non obvious, as we would need to use features of `ycm_ep_helper` that I do not really know if they have been tested a lot in the past. Probably just modifying `manifpy`  to support installing its Python bindings is the best option.

**Comment by traversaro** [comment]
> Maybe we can wait [artivis/manif#233](https://github.com/artivis/manif/pull/233)? However, this means that we cannot support the newly tagged release.

Cool, I did not saw that! This is not a big problem, if the PR is not merged soon I can quickly create a internal release on a fork and use that one, the proper release was just necessary for conda-forge.
